name: quickstart
modulepath: libs
downloadpath: libs
repo: https://github.com/inmanta/
description: A quickstart project that installs a drupal website.
requires:
    - apache~=0.3.0
    - drupal~=0.7.1
    - exec~=0.5.0
    - ip~=0.10.0
    - logging~=0.4
    - mysql~=0.5.2
    - net~=0.5.0
    - php~=0.3
    - redhat~=0.7.0
    - ssh~=0.3.1
    - std~=0.14.0
    - web~=0.2.2
    - yum~=0.5.0
